import google.generativeai as genai

class InstagramCommentSchema:
    """Schema definition for Instagram comments generated by the AI"""
    
    def __init__(self):
        self.description = "Lists comments that are engaging and have the potential to attract more likes and go viral."
        self.type = "ARRAY"
        self.items = {
            "type": "OBJECT",
            "properties": {
                "comment": {
                    "type": "STRING",
                    "description": "A comment between 150 and 250 characters.",
                    "nullable": False,
                },
                "viralRate": {
                    "type": "NUMBER",
                    "description": "The viral rate, measured on a scale of 0 to 100.",
                    "nullable": False,
                },
                "commentTokenCount": {
                    "type": "NUMBER",
                    "description": "The total number of tokens in the comment.",
                    "nullable": False,
                },
            },
            "required": ["comment", "viralRate", "commentTokenCount"]
        }

def get_instagram_comment_schema():
    """Returns the schema for Instagram comments"""
    schema = InstagramCommentSchema()
    return {
        "description": schema.description,
        "type": schema.type,
        "items": schema.items
    }